import type { RecommendationMap } from './types'

const recommendations: RecommendationMap = {
  // ── GROWTH ENGINE ────────────────────────────────────────────────────
  g1: {
    pillarId: 'g1',
    Foundational: 'Contradictory or inaccessible customer data is the most common reason growth programs underperform. Without unified customer profiles and clear governance, personalization programs are guessing and retention programs are reacting. Establish a customer identity strategy, assign clear data ownership, and implement consent management. This is the foundation on which our Hiper-Personalización a Escala and Predictive Retention Analytics playbooks are built — every dollar invested here multiplies the return on everything downstream.',
    Developing: 'You have the beginnings of a data foundation, but fragmentation is limiting what you can do downstream. Consolidate customer records into a single profile and prioritize enabling self-serve data access for marketing and commercial teams. Closing this gap is what makes our Predictive Retention Analytics playbook immediately actionable — moving from reactive to proactive retention at scale.',
    Scaling: 'Your customer data infrastructure is mature enough to power sophisticated programs. Focus now on real-time data capture across all channels and data quality automation — the fuel that makes Hiper-Personalización a Escala possible. Explore a Customer Data Platform (CDP) to automate profile enrichment and dynamic segmentation updates.',
    Leading: 'Your customer data foundation is a genuine competitive asset. The investment here is what makes best-in-class personalization and retention possible. Focus on deepening real-time behavioral signals and predictive enrichment to stay ahead of the market and maximize the lifetime value of your existing customer base.',
  },
  g2: {
    pillarId: 'g2',
    Foundational: 'Start with basic segmentation: define 3–5 core customer segments (new buyers, loyal customers, lapsed) and implement simple triggered personalization for each. Even basic relevance improvements drive meaningful revenue gains. This is the entry point for our Hiper-Personalización a Escala playbook — and the foundation is simpler to build than most teams expect.',
    Developing: 'Move from static to behavioral segments and enable automated personalization on your key revenue pages (homepage, category, cart). Implement A/B testing infrastructure to measure impact rigorously. Our Hiper-Personalización a Escala playbook is built to accelerate exactly this transition — from broad segments to real-time, behavior-driven experiences that convert at a higher rate.',
    Scaling: 'Expand personalization to the full customer journey and introduce machine learning-based product recommendations. Shift from broad segments to micro-segments and real-time decisioning. At this stage, our Hiper-Personalización a Escala playbook focuses on cross-channel orchestration and the infrastructure needed to personalize at scale without manual effort.',
    Leading: 'Your personalization capability is sophisticated and delivering results. The next frontier is full cross-channel orchestration — ensuring the experience is consistent whether the customer is on your site, receiving an email, or browsing a marketplace. Continue testing increasingly granular hypotheses to extract incremental revenue from your mature Hiper-Personalización foundation.',
  },
  g3: {
    pillarId: 'g3',
    Foundational: 'Define your customer lifecycle stages and build the first three automated flows: welcome series, first-purchase follow-up, and a basic lapsed-customer reactivation. These flows alone typically recover significant revenue. Our Predictive Retention Analytics playbook starts here — identifying your highest-risk customers and the specific actions that save them before they are gone.',
    Developing: 'Implement LTV tracking by cohort and channel, and build a churn risk scoring model using recency, frequency, and monetary (RFM) signals. Use scores to trigger proactive retention offers. Our Predictive Retention Analytics playbook provides the modeling framework and trigger logic to move you from reactive to predictive retention — protecting your most valuable customers before they churn.',
    Scaling: 'Deploy predictive churn models and personalize retention offers based on customer value tier. Measure and optimize the ROI of each lifecycle program with statistical rigor. This is where our Predictive Retention Analytics playbook drives its greatest financial impact — shifting from generic loyalty programs to precision retention that protects your highest-value customers at the moment they are most at risk.',
    Leading: 'Your lifecycle marketing is best-in-class. The next level is combining Predictive Retention Analytics with Hiper-Personalización a Escala — using behavioral signals not just to identify at-risk customers, but to serve exactly the right message, offer, and channel in the moment it matters most. Explore next-best-action engines to maximize LTV at scale.',
  },
  g4: {
    pillarId: 'g4',
    Foundational: 'Connect your first-party customer data to paid media platforms to enable audience targeting and suppression of existing customers. Establish a basic attribution framework. Ensure your marketplace presence has basic content and pricing governance in place — unmanaged marketplace listings erode both margin and brand equity. Our Performance Demand Generation playbook builds the foundation for scalable, data-driven customer acquisition across all channels.',
    Developing: 'Implement a multi-touch attribution model and use it to guide budget allocation decisions. Treat your marketplace channel as a structured revenue line — with analytics, pricing strategy, and listing optimization — not as a passive presence. Our Performance Demand Generation playbook aligns paid, owned, and marketplace channels around a unified acquisition strategy with clear ROI targets.',
    Scaling: 'Use customer segment data for advanced lookalike modeling and run systematic creative testing. Build a marketplace analytics practice that surfaces your best-performing listings, pricing opportunities, and competitive gaps. Our Performance Demand Generation playbook at this stage accelerates the shift from spend-based to outcome-based channel management.',
    Leading: 'Your channel optimization is sophisticated and data-driven. Invest in incrementality testing to separate true channel contribution from correlation, and build a closed-loop system where acquisition data feeds your retention and personalization programs. The combination of Performance Demand Generation and Predictive Retention Analytics is where the highest-LTV acquisition strategies are built.',
  },
  g5: {
    pillarId: 'g5',
    Foundational: 'Build a basic revenue reporting layer that delivers daily or weekly results by channel and product category without manual effort. Establish pricing visibility — understanding your current price positioning relative to competitors is the starting point for our Revenue & Pricing Science playbook, which unlocks the ability to optimize margin and volume simultaneously rather than trading one off against the other.',
    Developing: 'Introduce formal revenue forecasting and track leading indicators (conversion rate, average order value, repeat purchase rate) alongside top-line sales. Begin measuring price elasticity on your most important SKUs — even basic elasticity analysis reveals significant revenue optimization opportunities that our Revenue & Pricing Science playbook is designed to capture systematically.',
    Scaling: 'Use elasticity models to make proactive pricing decisions rather than reacting to competitive pressure or cost increases. Our Revenue & Pricing Science playbook at this stage focuses on consolidating margin visibility across your full catalog and building a pricing governance process that protects margin without sacrificing volume — turning pricing from a periodic review into a managed capability.',
    Leading: 'Your analytics and pricing intelligence are a strategic advantage. Focus on dynamic pricing capabilities and real-time margin optimization by channel. Our Revenue & Pricing Science playbook at this stage explores advanced demand sensing and algorithmic pricing to extract additional revenue from your existing catalog — making pricing a continuous optimization system rather than a scheduled decision.',
  },

  // ── EFFICIENCY ENGINE ────────────────────────────────────────────────
  e1: {
    pillarId: 'e1',
    Foundational: 'Contradictory data across departments is one of the most expensive invisible costs in any business — it slows decisions, erodes trust, and makes scaling harder than it needs to be. Our Gobernanza de Datos playbook starts here: defining a single version of truth for your key business metrics, assigning clear data ownership, and building the governance foundation that AI, automation, and advanced analytics are all built on top of. Without it, every downstream investment underperforms.',
    Developing: 'You have started to centralize data, but fragmentation between teams is still creating friction and contradictions. Consolidate into a shared data infrastructure, document ownership for each critical data domain, and invest in enabling self-serve access for commercial teams. Our Gobernanza de Datos playbook accelerates this transition — turning your data from a bottleneck into a strategic asset that every team can act on independently.',
    Scaling: 'Your data governance is functional. The next step is making it proactive and scalable — automated data cataloguing, lineage tracking, and self-serve analytics for operational teams. A mature Gobernanza de Datos implementation is also the prerequisite that makes the Gen AI and automation investments high-impact rather than high-risk.',
    Leading: 'Your data governance is excellent and serves as the foundation for every advanced analytics and AI initiative. Focus on extending real-time data availability, deepening your data catalog, and ensuring governance keeps pace with new data sources as the business grows. This is a compounding competitive advantage — every new capability you build benefits from it.',
  },
  e2: {
    pillarId: 'e2',
    Foundational: 'Decisions made on bad data are often worse than no decision at all — and the damage is invisible until it appears as a financial loss or an operational failure. Our Data Trust & Quality playbook begins by building confidence in your data: establishing quality benchmarks, introducing basic monitoring, and creating accountability when errors occur. This is foundational to every data-driven initiative across all three engines.',
    Developing: 'You have some quality practices in place, but gaps still reach reports and cause downstream errors. Implement automated monitoring to catch pipeline failures and anomalies before they surface to decision-makers. Our Data Trust & Quality playbook provides the monitoring frameworks and governance processes that transform your data from "probably right" to "reliably right" — the difference between a team that uses data and one that trusts it.',
    Scaling: 'Your data quality practices are maturing. Focus now on proactive monitoring — detecting drift, anomalies, and quality degradation in real time rather than after the fact. Establish formal SLAs for data freshness and accuracy, and embed root-cause analysis into your data operations cadence. This is what makes AI and advanced analytics trustworthy at scale, not just in demos.',
    Leading: 'Your data trust and quality practices are a competitive advantage — decision-makers across the business can act on data with confidence. Focus on predictive data quality: using ML to anticipate and prevent quality issues before they occur. Extend your monitoring systematically to every new data source as the business grows, so trust scales with the organization.',
  },
  e3: {
    pillarId: 'e3',
    Foundational: 'Most businesses today are either using AI unsystematically — individuals using public tools with no governance — or not at all. Both are leaving significant value on the table. Our Gen AI Corporativa playbook starts with the fundamentals: identifying your highest-value automation candidates and building a secure AI foundation that lets your teams work with AI on your own data without risk. The goal is not to automate everything — it is to delegate the right tasks to AI so your team focuses on higher-value work.',
    Developing: 'You have begun exploring AI and automation, but adoption is inconsistent and governance is limited. Our Gen AI Corporativa and Automatización de Flujos & API playbooks work together here — building secure infrastructure for AI on internal data while systematically automating your highest-volume repetitive processes. Even a small number of well-executed automations can recover significant operational capacity and reduce error rates.',
    Scaling: 'Your AI and automation capabilities are developing. Focus on expanding adoption systematically — identifying new automation candidates using data, building reusable AI components, and institutionalizing the evaluation process for new tools. Our Automatización de Flujos & API playbook at this stage focuses on chaining automations into end-to-end intelligent workflows rather than isolated point solutions.',
    Leading: 'Your AI and automation readiness is exceptional. You have the foundation to move from task automation to intelligent autonomous agents that manage entire operational workflows. Focus on scaling your most successful AI applications, measuring their financial impact rigorously, and building internal capability to continuously evaluate and adopt AI advances as they emerge.',
  },
  e4: {
    pillarId: 'e4',
    Foundational: 'Operational waste is rarely visible — it hides in approval chains, manual handoffs, rework loops, and processes nobody has questioned in years. Our Lean Six Sigma para la rentabilidad playbook starts by making waste visible: mapping core processes, measuring cycle times and error rates, and identifying the highest-ROI improvement opportunities. The financial impact of eliminating your top three process bottlenecks is typically larger than expected.',
    Developing: 'You have identified some inefficiencies but improvement efforts are reactive and isolated. Implement documented efficiency targets for your core processes and establish a regular improvement cadence. Our Lean Six Sigma para la rentabilidad playbook provides the framework to move from ad hoc fixes to systematic, measurable process improvement that compounds over time and directly impacts your profitability.',
    Scaling: 'Your process improvement capability is maturing. Focus on closing the loop between operational efficiency gains and financial outcomes — every process improvement should have a measurable P&L impact that is tracked and reported. Our Lean Six Sigma para la rentabilidad playbook at this stage introduces variance reduction and statistical process control to sustain gains rather than letting them erode.',
    Leading: 'Your operational efficiency is systematically managed and financially measured. The next frontier is combining process excellence with AI and automation — using Lean analysis to identify the processes most valuable to automate, and building a continuous improvement culture that operates without management intervention. This is where operational excellence becomes a scalable competitive moat.',
  },
  e5: {
    pillarId: 'e5',
    Foundational: 'A business that cannot scale without proportionally increasing headcount is a business whose growth is self-limiting. The first step is standardization: documenting core processes so a new hire can execute them, and identifying where tribal knowledge is creating operational fragility. Our Gobernanza de Datos and Lean Six Sigma playbooks together address the root causes of poor scalability — data fragmentation and process variability.',
    Developing: 'Your operations are beginning to scale but remain too dependent on specific individuals and manual intervention to absorb volume increases efficiently. Focus on process standardization, cross-training, and building redundancy into critical workflows. Operational resilience — the ability to absorb disruptions without service degradation — is the foundation of sustainable scaling.',
    Scaling: 'Your operations scale reasonably well, but capacity planning is still reactive rather than forward-looking. Build a capacity roadmap that anticipates your infrastructure, systems, and people needs ahead of demand. Our Automatización de Flujos & API playbook accelerates scalability by replacing headcount-dependent processes with intelligent, self-managing workflows that grow with volume without growing costs.',
    Leading: 'Your operational scalability is excellent — the business can absorb significant growth without proportional cost increases. Focus on maintaining this advantage as complexity grows: ensuring that new products, channels, and markets are onboarded within a scalable framework from the start, rather than adding complexity that needs to be rationalized later.',
  },

  // ── ADAPTABILITY ENGINE ──────────────────────────────────────────────
  a1: {
    pillarId: 'a1',
    Foundational: 'Prioritize integration of your core systems — e-commerce, OMS, and ERP — to eliminate manual reconciliation. Even basic event-driven integration between these three systems dramatically reduces operational friction and the errors that come from data living in multiple places. Document your architecture as you go: system ownership and data flows are organizational assets, not just technical details.',
    Developing: 'Document your architecture: system ownership, data flows, and API contracts. This reduces key-person dependency and accelerates future technology decisions. Begin addressing the highest-friction legacy integrations — the ones that require the most manual intervention or that break most often under volume.',
    Scaling: 'Adopt a composable architecture mindset: prefer best-of-breed integrations over monolithic platforms. Build internal capability to evaluate and onboard new vendors faster. The speed at which your organization can adopt new technology is increasingly a competitive differentiator — make it a measurable organizational capability.',
    Leading: 'Your technology stack is well-integrated and enables the business rather than constraining it. Focus on real-time data streaming across systems and building a platform that allows marketing and operations to self-serve new capabilities without engineering involvement. This is how technology becomes a growth enabler rather than a bottleneck.',
  },
  a2: {
    pillarId: 'a2',
    Foundational: 'Document your three most critical operational processes — order processing, new product launch, and returns handling — to a level where a new hire can execute them. This single action significantly reduces operational fragility and is the prerequisite for any meaningful process improvement or automation initiative that follows.',
    Developing: 'Establish a process ownership model and a quarterly review cadence. Introduce a lightweight continuous improvement mechanism — even a shared log where teams capture process failures and improvements. Connecting process performance to operational KPIs makes improvement visible and creates accountability without heavy governance overhead.',
    Scaling: 'Implement process compliance measurement for critical workflows and use data to drive improvement decisions. Connect process performance directly to operational KPIs so that improvement is visible in the numbers. At this stage, process discipline is what allows the organization to scale without adding management overhead.',
    Leading: 'Your process management is mature and self-sustaining. Focus on automation for repetitive, high-volume workflows and on building a continuous improvement culture that operates without management intervention. Process excellence at this level is a compounding advantage — every improvement makes the next one easier.',
  },
  a3: {
    pillarId: 'a3',
    Foundational: 'Define clear decision rights for your most frequent cross-functional decisions. A simple RACI for merchandising, marketing campaign approval, and technology investment will immediately reduce execution delays. Decision ambiguity is one of the most common and most fixable causes of slow time-to-market.',
    Developing: 'Align teams on shared OKRs that span commercial, marketing, and operations. Measure and report on time-to-market for new initiatives to create accountability for decision speed. When teams see cycle time as a metric, they naturally find ways to reduce it.',
    Scaling: 'Streamline approval processes to push decisions closer to the team level. Implement a test-and-learn framework that allows teams to move fast on low-risk commercial experiments without senior sign-off. Decision speed at scale requires trust, clarity, and a safety net — not more process.',
    Leading: 'Your decision-making is fast and well-aligned. Focus on building organizational structures that enable autonomous squads to test and scale new capabilities independently. At this level, the goal is not faster decisions from the center — it is fewer decisions that need to reach the center at all.',
  },
  a4: {
    pillarId: 'a4',
    Foundational: 'Equip your commercial teams with basic self-serve dashboards for their most critical decisions — inventory levels, sales by channel, and campaign performance. Removing the dependency on a data or analytics team for routine reporting is the single fastest way to improve decision speed across the organization.',
    Developing: 'Invest in data literacy training for commercial and operations teams. Implement data quality monitoring so that decision-makers trust the data they see. A team that has data access but does not trust the data makes decisions no better than one with no data at all.',
    Scaling: 'Expand self-serve analytics to include forecasting and scenario planning tools. Establish a data governance council to maintain shared definitions and quality standards across teams. At this stage, data literacy is an organizational capability that needs to be actively cultivated and measured — not assumed.',
    Leading: 'Your data culture is strong and self-reinforcing. Focus on embedding AI-assisted insights into daily workflows and enabling teams to act on predictive signals, not just historical reports. The next competitive advantage is not better data — it is faster and more confident action on the data you already have.',
  },
  a5: {
    pillarId: 'a5',
    Foundational: 'Introduce a basic change management checklist for your next major initiative: identify stakeholders, plan communications, and measure adoption at 30/60/90 days. This single habit significantly improves implementation success rates and reduces the rework that comes from changes not properly landed with the teams who need to execute them.',
    Developing: 'Institutionalize retrospectives as a standard project close-out activity. Create a visible mechanism for employees to raise process improvement ideas and ensure ideas receive a timely response. A culture of continuous improvement starts with making it safe and easy to surface what is not working.',
    Scaling: 'Build a formal change management capability and embed it in your project delivery methodology. Measure adoption rates for major technology and process changes and use that data to improve your change approach over time. Change management at scale is a discipline, not a checklist — it requires its own tools, skills, and accountability.',
    Leading: 'Your change management capability is a competitive differentiator. Focus on building organizational ambidexterity — the ability to run current operations with excellence while simultaneously designing and testing what comes next. Organizations that master this balance consistently outperform those that optimize for either stability or innovation alone.',
  },
}

export default recommendations
