import type { RecommendationMap } from './types'

const recommendations: RecommendationMap = {
  // ── MOTOR DE CRECIMIENTO ─────────────────────────────────────────────
  g1: {
    pillarId: 'g1',
    Foundational: 'Los datos de clientes contradictorios o inaccesibles son la razón más común por la que los programas de crecimiento underperforman. Sin perfiles unificados de clientes y gobernanza clara, los programas de personalización están adivinando y los de retención están reaccionando. Establece una estrategia de identidad de cliente, asigna responsabilidad clara sobre los datos e implementa la gestión de consentimientos. Esta es la base sobre la que se construyen nuestros playbooks de Hiper-Personalización a Escala y Predictive Retention Analytics — cada peso invertido aquí multiplica el retorno de todo lo que viene después.',
    Developing: 'Tienes los cimientos de una base de datos, pero la fragmentación está limitando lo que puedes hacer aguas abajo. Consolida los registros de clientes en un perfil único y prioriza habilitar el acceso autónomo a datos para los equipos de marketing y comercio. Cerrar esta brecha es lo que hace que nuestro playbook de Predictive Retention Analytics sea inmediatamente accionable — pasando de retención reactiva a proactiva a escala.',
    Scaling: 'Tu infraestructura de datos de clientes es lo suficientemente madura para impulsar programas sofisticados. Enfócate ahora en la captura de datos en tiempo real en todos los canales y en la automatización de calidad de datos — el combustible que hace posible Hiper-Personalización a Escala. Evalúa una Customer Data Platform (CDP) para automatizar el enriquecimiento de perfiles y la actualización dinámica de segmentos.',
    Leading: 'Tu base de datos de clientes es un activo competitivo genuino. La inversión aquí es lo que hace posible la personalización y la retención de primer nivel. Enfócate en profundizar las señales de comportamiento en tiempo real y el enriquecimiento predictivo para mantenerte por delante del mercado y maximizar el valor de vida de tu base de clientes actual.',
  },
  g2: {
    pillarId: 'g2',
    Foundational: 'Comienza con segmentación básica: define 3–5 segmentos clave de clientes (compradores nuevos, clientes leales, inactivos) e implementa personalización simple activada para cada uno. Incluso mejoras básicas de relevancia generan ganancias de ingresos significativas. Este es el punto de entrada de nuestro playbook Hiper-Personalización a Escala — y la base es más simple de construir de lo que la mayoría de los equipos espera.',
    Developing: 'Migra de segmentos estáticos a segmentos conductuales y habilita personalización automatizada en tus páginas de mayor conversión (home, categoría, carrito). Implementa infraestructura de A/B testing para medir el impacto con rigor. Nuestro playbook Hiper-Personalización a Escala está diseñado para acelerar exactamente esta transición — de segmentos amplios a experiencias en tiempo real basadas en comportamiento que convierten a mayor tasa.',
    Scaling: 'Expande la personalización a todo el customer journey e introduce recomendaciones de producto basadas en machine learning. Avanza de segmentos amplios a micro-segmentos y toma de decisiones en tiempo real. En esta etapa, nuestro playbook Hiper-Personalización a Escala se enfoca en la orquestación cross-channel y la infraestructura necesaria para personalizar a escala sin esfuerzo manual.',
    Leading: 'Tu capacidad de personalización es sofisticada y está generando resultados. La siguiente frontera es la orquestación cross-channel completa — asegurando que la experiencia sea consistente ya sea que el cliente esté en tu sitio, recibiendo un email o navegando en un marketplace. Continúa probando hipótesis cada vez más granulares para extraer ingresos incrementales de tu madura base de Hiper-Personalización.',
  },
  g3: {
    pillarId: 'g3',
    Foundational: 'Define las etapas del ciclo de vida de tus clientes y construye los primeros tres flujos automatizados: serie de bienvenida, seguimiento post-primera compra y reactivación básica de clientes inactivos. Estos flujos solos típicamente recuperan ingresos significativos. Nuestro playbook Predictive Retention Analytics comienza aquí — identificando tus clientes de mayor riesgo y las acciones específicas que los salvan antes de que se vayan.',
    Developing: 'Implementa el seguimiento de LTV por cohorte y canal, y construye un modelo de riesgo de churn usando señales de recencia, frecuencia y valor monetario (RFM). Usa los puntajes para activar ofertas de retención proactivas. Nuestro playbook Predictive Retention Analytics provee el framework de modelado y la lógica de activación para moverte de retención reactiva a predictiva — protegiendo tus clientes más valiosos antes de que se vayan.',
    Scaling: 'Despliega modelos predictivos de churn y personaliza las ofertas de retención según el nivel de valor del cliente. Mide y optimiza el ROI de cada programa de ciclo de vida con rigor estadístico. Aquí es donde nuestro playbook Predictive Retention Analytics genera su mayor impacto financiero — pasando de programas de lealtad genéricos a retención de precisión que protege a tus clientes de mayor valor en el momento en que están más en riesgo.',
    Leading: 'Tu marketing de ciclo de vida es de primer nivel. El siguiente nivel es combinar Predictive Retention Analytics con Hiper-Personalización a Escala — usando señales de comportamiento no solo para identificar clientes en riesgo, sino para servirles exactamente el mensaje, oferta y canal correctos en el momento que importa. Explora motores de "next-best-action" para maximizar el LTV a escala.',
  },
  g4: {
    pillarId: 'g4',
    Foundational: 'Conecta tus datos propios de clientes a las plataformas de medios pagados para habilitar la segmentación de audiencias y la exclusión de clientes actuales. Establece un framework básico de atribución. Asegúrate de que tu presencia en marketplace tenga gobernanza básica de contenido y precios — los listings no gestionados erosionan tanto el margen como el equity de marca. Nuestro playbook Performance Demand Generation construye la base para la adquisición de clientes escalable y basada en datos en todos los canales.',
    Developing: 'Implementa un modelo de atribución multi-touch y úsalo para guiar las decisiones de inversión por canal. Trata tu canal de marketplace como una línea de ingresos estructurada — con analítica, estrategia de precios y optimización de listings — no como una presencia pasiva. Nuestro playbook Performance Demand Generation alinea los canales pagados, propios y de marketplace alrededor de una estrategia de adquisición unificada con objetivos claros de ROI.',
    Scaling: 'Usa datos de segmentos de clientes para modelado avanzado de audiencias similares y realiza pruebas sistemáticas de creatividades. Construye una práctica de analítica de marketplace que identifique tus mejores listings, oportunidades de precio y brechas competitivas. Nuestro playbook Performance Demand Generation en esta etapa acelera el cambio de gestión basada en gasto a gestión basada en resultados.',
    Leading: 'Tu optimización de canales es sofisticada y basada en datos. Invierte en pruebas de incrementalidad para separar la contribución real de cada canal de la correlación, y construye un sistema de ciclo cerrado donde los datos de adquisición alimenten tus programas de retención y personalización. La combinación de Performance Demand Generation y Predictive Retention Analytics es donde se construyen las estrategias de adquisición con mayor LTV.',
  },
  g5: {
    pillarId: 'g5',
    Foundational: 'Construye una capa básica de reporte de ingresos que entregue resultados diarios o semanales por canal y categoría de producto sin esfuerzo manual. Establece visibilidad de precios — entender tu posicionamiento de precio actual frente a la competencia es el punto de partida de nuestro playbook Revenue & Pricing Science, que desbloquea la capacidad de optimizar margen y volumen simultáneamente en lugar de sacrificar uno por el otro.',
    Developing: 'Introduce pronósticos formales de ingresos y haz seguimiento de indicadores adelantados (tasa de conversión, ticket promedio, tasa de recompra) además de las ventas históricas. Comienza a medir la elasticidad de precio en tus SKUs más importantes — incluso un análisis básico de elasticidad revela oportunidades de optimización de ingresos significativas que nuestro playbook Revenue & Pricing Science está diseñado para capturar sistemáticamente.',
    Scaling: 'Usa modelos de elasticidad para tomar decisiones de precio proactivas en lugar de reaccionar ante presión competitiva o aumentos de costo. Nuestro playbook Revenue & Pricing Science en esta etapa se enfoca en consolidar la visibilidad de margen en todo tu catálogo y construir un proceso de gobernanza de precios que proteja el margen sin sacrificar volumen — convirtiendo el pricing de una revisión periódica a una capacidad gestionada.',
    Leading: 'Tu analítica e inteligencia de precios son una ventaja estratégica. Enfócate en capacidades de precio dinámico y optimización de margen en tiempo real por canal. Nuestro playbook Revenue & Pricing Science en esta etapa explora el demand sensing avanzado y el pricing algorítmico para extraer ingresos adicionales de tu catálogo existente — haciendo del precio un sistema de optimización continua en lugar de una decisión programada.',
  },

  // ── MOTOR DE EFICIENCIA ──────────────────────────────────────────────
  e1: {
    pillarId: 'e1',
    Foundational: 'Los datos contradictorios entre departamentos son uno de los costos invisibles más costosos en cualquier negocio — ralentizan las decisiones, erosionan la confianza y hacen el escalamiento más difícil de lo necesario. Nuestro playbook Gobernanza de Datos comienza aquí: definiendo una única versión de la verdad para tus métricas clave, asignando responsabilidad clara sobre los datos y construyendo la base de gobernanza sobre la que se construyen la IA, la automatización y la analítica avanzada. Sin ella, cada inversión aguas abajo rinde por debajo de su potencial.',
    Developing: 'Has comenzado a centralizar datos, pero la fragmentación entre equipos todavía genera fricción y contradicciones. Consolida en una infraestructura de datos compartida, documenta los responsables de cada dominio de datos crítico y habilita el acceso autónomo para los equipos comerciales. Nuestro playbook Gobernanza de Datos acelera esta transición — convirtiendo tus datos de un cuello de botella en un activo estratégico que cada equipo puede utilizar de forma independiente.',
    Scaling: 'Tu gobernanza de datos es funcional. El siguiente paso es hacerla proactiva y escalable — catalogación automática de datos, rastreo de linaje y analítica de autoservicio para equipos operacionales. Una implementación madura de Gobernanza de Datos es también el prerrequisito que hace que las inversiones en Gen AI y automatización sean de alto impacto en lugar de alto riesgo.',
    Leading: 'Tu gobernanza de datos es excelente y sirve como base para cada iniciativa de analítica avanzada e IA. Enfócate en extender la disponibilidad de datos en tiempo real, profundizar tu catálogo de datos y asegurar que la gobernanza mantenga el ritmo con las nuevas fuentes de datos a medida que el negocio crece. Esta es una ventaja competitiva que se compone — cada nueva capacidad que construyes se beneficia de ella.',
  },
  e2: {
    pillarId: 'e2',
    Foundational: 'Las decisiones tomadas con datos incorrectos suelen ser peores que no decidir — y el daño es invisible hasta que aparece como una pérdida financiera o una falla operacional. Nuestro playbook Data Trust & Quality comienza por construir confianza en tus datos: estableciendo benchmarks de calidad, introduciendo monitoreo básico y creando responsabilidad cuando ocurren errores. Esto es fundamental para cada iniciativa basada en datos en los tres motores.',
    Developing: 'Tienes algunas prácticas de calidad implementadas, pero las brechas todavía llegan a los reportes y generan errores aguas abajo. Implementa monitoreo automatizado para detectar fallas en pipelines y anomalías antes de que lleguen a los tomadores de decisiones. Nuestro playbook Data Trust & Quality provee los frameworks de monitoreo y los procesos de gobernanza que transforman tus datos de "probablemente correcto" a "confiablemente correcto" — la diferencia entre un equipo que usa datos y uno que confía en ellos.',
    Scaling: 'Tus prácticas de calidad de datos están madurando. Enfócate ahora en el monitoreo proactivo — detectando drift, anomalías y degradación de calidad en tiempo real en lugar de después del hecho. Establece SLAs formales para la frescura y exactitud de datos, e integra el análisis de causa raíz en tu cadencia de operaciones de datos. Esto es lo que hace que la IA y la analítica avanzada sean confiables a escala, no solo en demos.',
    Leading: 'Tus prácticas de confianza y calidad de datos son una ventaja competitiva — los tomadores de decisiones en todo el negocio pueden actuar con confianza sobre los datos. Enfócate en calidad de datos predictiva: usar ML para anticipar y prevenir problemas de calidad antes de que ocurran. Extiende tu monitoreo sistemáticamente a cada nueva fuente de datos a medida que el negocio crece, para que la confianza escale con la organización.',
  },
  e3: {
    pillarId: 'e3',
    Foundational: 'La mayoría de los negocios hoy están usando IA de forma asistemática — personas usando herramientas públicas sin gobernanza — o no la están usando en absoluto. Ambas situaciones dejan valor significativo sobre la mesa. Nuestro playbook Gen AI Corporativa comienza con los fundamentos: identificando tus candidatos de automatización de mayor valor y construyendo una base de IA segura que permita a tus equipos trabajar con IA sobre tus propios datos sin riesgo. El objetivo no es automatizarlo todo — es delegar las tareas correctas a la IA para que tu equipo se enfoque en trabajo de mayor valor.',
    Developing: 'Has comenzado a explorar IA y automatización, pero la adopción es inconsistente y la gobernanza es limitada. Nuestros playbooks Gen AI Corporativa y Automatización de Flujos & API trabajan juntos aquí — construyendo infraestructura segura para IA sobre datos internos mientras automatizan sistemáticamente tus procesos repetitivos de mayor volumen. Incluso un pequeño número de automatizaciones bien ejecutadas puede recuperar capacidad operacional significativa y reducir tasas de error.',
    Scaling: 'Tus capacidades de IA y automatización están desarrollándose. Enfócate en expandir la adopción sistemáticamente — identificando nuevos candidatos de automatización usando datos, construyendo componentes de IA reutilizables e institucionalizando el proceso de evaluación para nuevas herramientas. Nuestro playbook Automatización de Flujos & API en esta etapa se enfoca en encadenar automatizaciones en flujos de trabajo inteligentes de extremo a extremo en lugar de soluciones puntuales aisladas.',
    Leading: 'Tu preparación para IA y automatización es excepcional. Tienes la base para pasar de automatización de tareas a agentes autónomos inteligentes que gestionan flujos de trabajo operacionales completos. Enfócate en escalar tus aplicaciones de IA más exitosas, medir su impacto financiero con rigor y construir capacidad interna para evaluar y adoptar continuamente los avances de IA a medida que emergen.',
  },
  e4: {
    pillarId: 'e4',
    Foundational: 'El desperdicio operacional rara vez es visible — se oculta en cadenas de aprobación, transferencias manuales, ciclos de retrabajo y procesos que nadie ha cuestionado en años. Nuestro playbook Lean Six Sigma para la rentabilidad comienza por hacer visible el desperdicio: mapeando procesos clave, midiendo tiempos de ciclo y tasas de error, e identificando las oportunidades de mejora con mayor ROI. El impacto financiero de eliminar tus tres principales cuellos de botella típicamente supera las expectativas.',
    Developing: 'Has identificado algunas ineficiencias pero los esfuerzos de mejora son reactivos y aislados. Implementa objetivos de eficiencia documentados para tus procesos clave y establece una cadencia regular de mejora. Nuestro playbook Lean Six Sigma para la rentabilidad provee el framework para pasar de correcciones ad hoc a mejora de procesos sistemática y medible que se acumula con el tiempo e impacta directamente tu rentabilidad.',
    Scaling: 'Tu capacidad de mejora de procesos está madurando. Enfócate en cerrar el ciclo entre las ganancias de eficiencia operacional y los resultados financieros — cada mejora de proceso debe tener un impacto medible en el P&L que se rastrea y reporta. Nuestro playbook Lean Six Sigma para la rentabilidad en esta etapa introduce reducción de varianza y control estadístico de procesos para sostener las ganancias en lugar de dejar que se erosionen.',
    Leading: 'Tu eficiencia operacional está gestionada sistemáticamente y medida financieramente. La siguiente frontera es combinar la excelencia de procesos con IA y automatización — usando el análisis Lean para identificar los procesos más valiosos de automatizar, y construyendo una cultura de mejora continua que opera sin intervención de la gerencia. Aquí es donde la excelencia operacional se convierte en un foso competitivo escalable.',
  },
  e5: {
    pillarId: 'e5',
    Foundational: 'Un negocio que no puede escalar sin aumentar proporcionalmente el personal es un negocio cuyo crecimiento se autolimita. El primer paso es la estandarización: documentar los procesos clave para que un nuevo integrante pueda ejecutarlos, e identificar dónde el conocimiento tribal está creando fragilidad operacional. Nuestros playbooks Gobernanza de Datos y Lean Six Sigma abordan juntos las causas raíz de la mala escalabilidad — la fragmentación de datos y la variabilidad de procesos.',
    Developing: 'Tus operaciones están comenzando a escalar pero siguen siendo demasiado dependientes de individuos específicos y de la intervención manual para absorber aumentos de volumen eficientemente. Enfócate en la estandarización de procesos, el entrenamiento cruzado y la construcción de redundancia en los flujos de trabajo críticos. La resiliencia operacional — la capacidad de absorber disrupciones sin degradación del servicio — es la base del escalamiento sostenible.',
    Scaling: 'Tus operaciones escalan razonablemente bien, pero la planificación de capacidad sigue siendo reactiva en lugar de prospectiva. Construye un roadmap de capacidad que anticipe tus necesidades de infraestructura, sistemas y personas por delante de la demanda. Nuestro playbook Automatización de Flujos & API acelera la escalabilidad reemplazando procesos dependientes de personal con flujos de trabajo inteligentes y autogestionados que crecen con el volumen sin crecer los costos.',
    Leading: 'Tu escalabilidad operacional es excelente — el negocio puede absorber un crecimiento significativo sin aumentos proporcionales de costos. Enfócate en mantener esta ventaja a medida que la complejidad crece: asegurando que nuevos productos, canales y mercados se incorporen dentro de un framework escalable desde el inicio, en lugar de agregar complejidad que necesite racionalizarse después.',
  },

  // ── MOTOR DE ADAPTABILIDAD ───────────────────────────────────────────
  a1: {
    pillarId: 'a1',
    Foundational: 'Prioriza la integración de tus sistemas principales — e-commerce, OMS y ERP — para eliminar la conciliación manual. Incluso una integración básica dirigida por eventos entre estos tres sistemas reduce drásticamente la fricción operacional y los errores que resultan de datos que viven en múltiples lugares. Documenta tu arquitectura a medida que avanzas: el ownership de sistemas y los flujos de datos son activos organizacionales, no solo detalles técnicos.',
    Developing: 'Documenta tu arquitectura: ownership de sistemas, flujos de datos y contratos de API. Esto reduce la dependencia de personas clave y acelera futuras decisiones tecnológicas. Comienza a abordar las integraciones legadas de mayor fricción — las que requieren más intervención manual o que fallan con mayor frecuencia bajo volumen.',
    Scaling: 'Adopta una mentalidad de arquitectura componible: prefiere integraciones best-of-breed sobre plataformas monolíticas. Construye capacidad interna para evaluar e incorporar nuevos proveedores con mayor rapidez. La velocidad con la que tu organización puede adoptar nueva tecnología es cada vez más un diferenciador competitivo — conviértela en una capacidad organizacional medible.',
    Leading: 'Tu stack tecnológico está bien integrado y habilita el negocio en lugar de limitarlo. Enfócate en el streaming de datos en tiempo real entre sistemas y en construir una plataforma que permita a marketing y operaciones autoabastecerse de nuevas capacidades sin involucrar a ingeniería. Así es como la tecnología se convierte en un habilitador de crecimiento en lugar de un cuello de botella.',
  },
  a2: {
    pillarId: 'a2',
    Foundational: 'Documenta tus tres procesos operacionales más críticos — procesamiento de pedidos, lanzamiento de nuevos productos y gestión de devoluciones — a un nivel en que un nuevo empleado pueda ejecutarlos. Esta sola acción reduce significativamente la fragilidad operacional y es el prerrequisito para cualquier iniciativa de mejora de procesos o automatización que siga.',
    Developing: 'Establece un modelo de ownership de procesos y una cadencia de revisión trimestral. Introduce un mecanismo liviano de mejora continua — incluso un log compartido donde los equipos capturen fallas y mejoras de procesos. Conectar el desempeño de procesos con los KPIs operacionales hace visible la mejora y crea responsabilidad sin sobrecarga de gobernanza.',
    Scaling: 'Implementa medición del apego a procesos para los flujos críticos y usa datos para impulsar decisiones de mejora. Conecta el desempeño de procesos directamente con los KPIs operacionales para que la mejora sea visible en los números. En esta etapa, la disciplina de procesos es lo que permite a la organización escalar sin agregar overhead de gestión.',
    Leading: 'Tu gestión de procesos es madura y autosostenida. Enfócate en la automatización de flujos repetitivos de alto volumen y en construir una cultura de mejora continua que opere sin intervención de la gerencia. La excelencia de procesos a este nivel es una ventaja que se compone — cada mejora hace la siguiente más fácil.',
  },
  a3: {
    pillarId: 'a3',
    Foundational: 'Define derechos de decisión claros para tus decisiones transversales más frecuentes. Un RACI simple para merchandising, aprobación de campañas de marketing e inversión tecnológica reducirá inmediatamente los retrasos en la ejecución. La ambigüedad en la toma de decisiones es una de las causas más comunes y más solucionables del lento tiempo hasta el mercado.',
    Developing: 'Alinea a los equipos en OKRs compartidos que abarquen las áreas comercial, marketing y operaciones. Mide y reporta el tiempo hasta el mercado para nuevas iniciativas para generar responsabilidad sobre la velocidad de decisión. Cuando los equipos ven el tiempo de ciclo como una métrica, naturalmente encuentran formas de reducirlo.',
    Scaling: 'Simplifica los procesos de aprobación para llevar las decisiones al nivel del equipo. Implementa un framework de prueba y aprendizaje que permita a los equipos moverse rápido en experimentos comerciales de bajo riesgo sin requerir aprobación senior. La velocidad de decisión a escala requiere confianza, claridad y una red de seguridad — no más proceso.',
    Leading: 'Tu toma de decisiones es rápida y bien alineada. Enfócate en construir estructuras organizacionales que permitan a equipos autónomos probar y escalar nuevas capacidades de forma independiente. En este nivel, el objetivo no es decisiones más rápidas desde el centro — es menos decisiones que necesiten llegar al centro.',
  },
  a4: {
    pillarId: 'a4',
    Foundational: 'Equipa a tus equipos comerciales con dashboards básicos de autoservicio para sus decisiones más críticas — niveles de inventario, ventas por canal y desempeño de campañas. Eliminar la dependencia del equipo de datos o analítica para el reporte de rutina es la forma más rápida de mejorar la velocidad de decisión en toda la organización.',
    Developing: 'Invierte en capacitación de alfabetización de datos para equipos comerciales y de operaciones. Implementa monitoreo de calidad de datos para que los tomadores de decisiones confíen en los datos que ven. Un equipo que tiene acceso a datos pero no confía en ellos toma decisiones no mejores que uno sin datos.',
    Scaling: 'Amplía la analítica de autoservicio para incluir herramientas de pronóstico y planificación de escenarios. Establece un consejo de gobernanza de datos para mantener definiciones compartidas y estándares de calidad entre equipos. En esta etapa, la alfabetización de datos es una capacidad organizacional que debe cultivarse y medirse activamente — no asumirse.',
    Leading: 'Tu cultura de datos es sólida y se autorreinforza. Enfócate en integrar insights asistidos por IA en los flujos de trabajo diarios y en habilitar a los equipos para actuar sobre señales predictivas, no solo reportes históricos. La siguiente ventaja competitiva no son mejores datos — es una acción más rápida y segura sobre los datos que ya tienes.',
  },
  a5: {
    pillarId: 'a5',
    Foundational: 'Introduce una lista de verificación básica de gestión del cambio para tu próxima iniciativa importante: identifica stakeholders, planifica comunicaciones y mide la adopción a los 30/60/90 días. Este solo hábito mejora significativamente las tasas de éxito en implementación y reduce el retrabajo que resulta de cambios que no fueron correctamente aterrizados con los equipos que necesitan ejecutarlos.',
    Developing: 'Institucionaliza las retrospectivas como una actividad estándar de cierre de proyecto. Crea un mecanismo visible para que los empleados propongan mejoras de procesos y asegúrate de que las ideas reciban una respuesta oportuna. Una cultura de mejora continua comienza por hacer que sea seguro y fácil señalar lo que no está funcionando.',
    Scaling: 'Construye una capacidad formal de gestión del cambio e intégrala en tu metodología de entrega de proyectos. Mide las tasas de adopción de los cambios tecnológicos y de procesos más importantes y usa esos datos para mejorar tu enfoque con el tiempo. La gestión del cambio a escala es una disciplina, no un checklist — requiere sus propias herramientas, habilidades y responsabilidades.',
    Leading: 'Tu capacidad de gestión del cambio es un diferenciador competitivo. Enfócate en construir la ambidestreza organizacional — la capacidad de operar las operaciones actuales con excelencia mientras simultáneamente diseñas y pruebas lo que viene después. Las organizaciones que dominan este equilibrio superan consistentemente a las que optimizan solo por estabilidad o solo por innovación.',
  },
}

export default recommendations
